# Generated by Django 4.2.5 on 2023-11-04 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemon', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
