# Generated by Django 4.2.5 on 2023-10-14 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_crew',
            new_name='assigned_to',
        ),
    ]
